[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  command = "npm run build && npm run export"
  publish = "/dist"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200